version: '3.7'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ${SQL_INIT_FILE}:/docker-entrypoint-initdb.d/init.sql
    restart: always
    ports:
      - 3306:3306

  app:
    build: ./src
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./src:/usr/src
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - db
